[package]
name = "day4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.31.2"
bitcoincore-rpc = "0.18.0"
dotenv = "0.15.0"
lazy_static = "1.4.0"
quickcheck = "1.0.3"
